import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

import { generatePyGMT } from '../src/scripts/pygmt.js';
import { generateRScript } from '../src/scripts/rscript.js';

import { FIXTURE } from './fixture.js';

/** A stripped-down variant: no title/contours/stations/furniture, reversed. */
function minimalState() {
  const s = structuredClone(FIXTURE);
  s.title = null;
  s.reverse = true;
  s.contours = null;
  s.hillshade = false;
  s.stations = null;
  s.furniture = { scaleBar: false, northArrow: false, graticuleDeg: 0, inset: false };
  s.journal = { title: null, widthMm: 90, dpi: 300, format: 'png', minFontPt: 6 };
  s.citations = [];
  return s;
}

/* ------------------------------------------------------------- PyGMT ----- */

test('PyGMT: WIDTH substituted, -J stripped, region in GMT order', () => {
  const py = generatePyGMT(FIXTURE);
  assert.ok(!py.includes('WIDTH'), 'WIDTH token must be substituted');
  // 168 mm -> 16.8 cm; PyGMT takes the -J value without the "-J" prefix.
  assert.ok(py.includes('projection = "L15/38/32.7/43.3/16.8c"'), 'final projection string');
  assert.ok(py.includes('region = [-6, 36, 30, 46]'), 'region list [W, E, S, N]');
  assert.ok(py.includes('import pygmt'), 'imports pygmt');
});

test('PyGMT: relief resolution follows the longitude-span rules', () => {
  // Mediterranean fixture: lon span 42° -> '02m'.
  assert.match(generatePyGMT(FIXTURE), /resolution="02m"/);

  const variant = (west, east) => {
    const s = structuredClone(FIXTURE);
    s.region = { west, south: -10, east, north: 10 };
    s.furniture.inset = false;
    return generatePyGMT(s);
  };
  assert.match(variant(-40, 40), /resolution="10m"/); // 80° >= 60
  assert.match(variant(0, 10), /resolution="30s"/); //   10° in [5, 20)
  assert.match(variant(0, 3), /resolution="15s"/); //     3° < 5
});

test('PyGMT: makecpt series, cmocean name and reverse flag', () => {
  const py = generatePyGMT(FIXTURE);
  assert.ok(
    py.includes('pygmt.makecpt(cmap="deep", series=[-6000, 0], reverse=True)'),
    'reverse=True for the shallow-light default (elevation axis)',
  );
  assert.match(py, /GMT >= 6 ships the cmocean colormaps natively/);

  const rev = generatePyGMT(minimalState());
  assert.ok(
    rev.includes('pygmt.makecpt(cmap="deep", series=[-6000, 0])') && !rev.includes('reverse=True'),
    'no reverse flag when the on-screen colormap is reversed',
  );
});

test('PyGMT: layer order — grdimage, then coast, then grdcontour', () => {
  const py = generatePyGMT(FIXTURE);
  const iImage = py.indexOf('fig.grdimage(');
  const iCoast = py.indexOf('fig.coast(shorelines=');
  const iContour = py.indexOf('fig.grdcontour(');
  assert.ok(iImage >= 0 && iCoast > iImage, 'coast comes after grdimage');
  assert.ok(iContour > iCoast, 'contours come after coast');
  assert.match(py, /shading="\+a315\+nt0\.6"/);
  assert.ok(py.includes('levels=500') && py.includes('annotation=1000'), 'contour intervals');
  assert.ok(py.includes('limit=[-6000, 0]'), 'contour depth limit');
});

test('PyGMT: stations — coords, mm->cm symbol, apostrophe-safe labels', () => {
  const py = generatePyGMT(FIXTURE);
  assert.ok(py.includes('station_lons = [21.13, 21.38]'), 'station lons');
  assert.ok(py.includes('station_lats = [36.57, 35.3]'), 'station lats');
  assert.ok(py.includes('style="c0.25c"'), '2.5 mm symbol -> 0.25 cm');
  assert.ok(py.includes('fill="#e4572e"'), 'station fill colour');
  assert.ok(py.includes('"L\'Atalante Basin"'), 'apostrophe survives inside double quotes');
  assert.match(py, /fig\.text\(.*font="7p,Helvetica,black"\)/, 'labels at journal min font');
});

test('PyGMT: frame, scale bar, north arrow, colorbar, inset', () => {
  const py = generatePyGMT(FIXTURE);
  assert.ok(
    py.includes(
      'fig.basemap(frame=["xa5f", "ya5f", "WSen+t\\"Mediterranean Sea — Bathymetry and Stations\\""])',
    ),
    'frame with graticule and quoted title',
  );
  // 111.32 * cos(38°) * 42 / 4 ≈ 921 km -> nice value 1000 km.
  assert.ok(py.includes('map_scale="jBL+w1000k+o0.4c/0.4c+f+lkm"'), 'nice 1000 km scale bar');
  assert.ok(py.includes('rose="jTR+w1.1c+o0.3c"'), 'north arrow');
  assert.ok(py.includes('fig.colorbar(frame="xaf+l\\"Elevation (m)\\"")'), 'colorbar');
  assert.ok(py.includes('with fig.inset(position="jTL+w3.2c+o0.25c"'), 'inset context');
  assert.ok(py.includes('projection="G15/38/3.2c"'), 'ortho inset centred on the region');
  assert.ok(py.includes('pen="1p,red"'), 'red region outline in inset');
});

test('PyGMT: header carries journal target, citations and install hint', () => {
  const py = generatePyGMT(FIXTURE);
  assert.match(py, /generated by Marine Map Tool/);
  assert.match(py, /Deep-Sea Research Part I/);
  assert.match(py, /width 168 mm \| 600 dpi \| PDF/);
  assert.match(py, /Lambert conformal conic/);
  for (const needle of ['GEBCO Compilation Group (2024)', 'Thyng, K. M.', 'ETOPO 2022']) {
    assert.ok(py.includes(needle), `citation present: ${needle}`);
  }
  assert.match(py, /Data accessed {2}: 2026-07-05/);
  assert.ok(
    py.includes('# pip install pygmt  (or conda install -c conda-forge pygmt)'),
    'install hint',
  );
});

test('PyGMT: savefig with journal dpi/format and width comment', () => {
  const py = generatePyGMT(FIXTURE);
  assert.ok(py.includes('fig.savefig("marine_map.pdf", dpi=600)'), 'savefig call');
  assert.match(py, /Final physical width: 168 mm \(16\.8 cm\) at 600 dpi/);
});

test('PyGMT: optional blocks vanish cleanly in the minimal state', () => {
  const py = generatePyGMT(minimalState());
  assert.ok(!py.includes('grdcontour'), 'no contours');
  assert.ok(!py.includes('station_lons'), 'no stations');
  assert.ok(!py.includes('shading='), 'no hillshade');
  assert.ok(!py.includes('map_scale'), 'no scale bar');
  assert.ok(!py.includes('rose='), 'no north arrow');
  assert.ok(!py.includes('fig.inset'), 'no inset');
  assert.ok(py.includes('frame=["xaf", "yaf", "WSen"]'), 'auto graticule, no +t title');
  assert.ok(py.includes('Generic (no journal)'), 'generic journal label');
  assert.ok(py.includes('fig.savefig("marine_map.png", dpi=300)'), 'png at 300 dpi');
});

test('PyGMT: emitted scripts are real Python 3 syntax (py_compile)', (t) => {
  const probe = spawnSync('python3', ['--version'], { encoding: 'utf8' });
  if (probe.error || probe.status !== 0) {
    t.skip('python3 not available on PATH');
    return;
  }
  const dir = fs.mkdtempSync(path.join(process.env.TMPDIR ?? '/tmp', 'mmt-scripts-'));
  try {
    for (const [label, state] of [
      ['full', FIXTURE],
      ['minimal', minimalState()],
    ]) {
      const file = path.join(dir, `figure-${label}.py`);
      fs.writeFileSync(file, generatePyGMT(state), 'utf8');
      const run = spawnSync('python3', ['-m', 'py_compile', file], { encoding: 'utf8' });
      assert.equal(run.status, 0, `py_compile failed for ${label} state:\n${run.stderr}`);
    }
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

/* ------------------------------------------------------------------ R ---- */

test('R: ERDDAP URL puts south:north then west:east in the slice slots', () => {
  const r = generateRScript(FIXTURE);
  assert.match(r, /ETOPO_2022_v1_15s\.nc/);
  assert.ok(r.includes('?z%5B(30):5:(46)%5D%5B(-6):5:(36)%5D'), 'z[(S):(N)][(W):(E)] slice');
  assert.ok(r.includes('download.file(bathy_url, destfile = "bathy.nc", mode = "wb")'));
  assert.ok(r.includes('terra::rast("bathy.nc")'));
  assert.ok(r.includes('names(bathy_df) <- c("lon", "lat", "z")'));
});

test('R: cmocean colours, limits, squish and reverse direction', () => {
  const r = generateRScript(FIXTURE);
  assert.ok(r.includes('cmocean::cmocean("deep", direction = -1)(256)'), 'shallow-light colormap (inverted for elevation axis)');
  assert.ok(r.includes('limits = c(-6000, 0)'), 'fill limits');
  assert.ok(r.includes('oob = scales::squish'), 'out-of-bounds squish');

  const rev = generateRScript(minimalState());
  assert.ok(rev.includes('cmocean::cmocean("deep", direction = 1)(256)'), 'reversed colormap');
});

test('R: contours, land, stations and furniture per state', () => {
  const r = generateRScript(FIXTURE);
  assert.ok(r.includes('breaks = seq(-6000, 0, by = 500)'), 'contour breaks');
  assert.ok(
    r.includes('rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")'),
    'Natural Earth land',
  );
  assert.ok(r.includes('lon = c(21.13, 21.38)'), 'station lons');
  assert.ok(r.includes('"L\'Atalante Basin"'), 'apostrophe-safe station name');
  assert.ok(r.includes('annotation_scale(location = "bl")'), 'scale bar');
  assert.ok(r.includes('annotation_north_arrow('), 'north arrow');
  assert.ok(r.includes('coord_sf('), 'coord_sf frame');
  assert.ok(r.includes('xlim = c(-6, 36)') && r.includes('ylim = c(30, 46)'), 'limits');
  assert.ok(r.includes('crs = sf::st_crs(4326)'), 'WGS84 crs');
  assert.ok(
    r.includes('labs(title = "Mediterranean Sea — Bathymetry and Stations")'),
    'title',
  );
  assert.ok(
    r.includes('theme_minimal(base_size = 8, base_family = "Helvetica")'),
    'base size = minFontPt + 1',
  );
});

test('R: ggsave carries journal width/dpi; eps falls back to pdf', () => {
  const r = generateRScript(FIXTURE);
  assert.ok(
    r.includes('ggsave("marine_map.pdf", plot = p, width = 168, units = "mm", dpi = 600)'),
    'ggsave call',
  );

  const eps = structuredClone(FIXTURE);
  eps.journal.format = 'eps';
  const rEps = generateRScript(eps);
  assert.ok(rEps.includes('ggsave("marine_map.pdf"'), 'eps falls back to pdf');
  assert.match(rEps, /cannot be written reliably by ggsave\(\)/);

  const tiff = structuredClone(FIXTURE);
  tiff.journal.format = 'tiff';
  assert.ok(generateRScript(tiff).includes('ggsave("marine_map.tiff"'), 'tiff passes through');
});

test('R: header notes the suggested projection and the plate carrée caveat', () => {
  const r = generateRScript(FIXTURE);
  assert.match(r, /Suggested projection : Lambert conformal conic/);
  assert.match(r, /plate carrée/);
  assert.match(r, /companion PyGMT script/);
  assert.ok(r.includes('install.packages(c("terra", "sf", "ggplot2", "cmocean",'));
  assert.ok(r.includes('"rnaturalearth", "rnaturalearthdata", "ggspatial"))'));
  assert.ok(r.includes('GEBCO Compilation Group (2024)'), 'citations embedded');
});

test('R: no unreplaced tokens or leaked JS values in either state', () => {
  for (const state of [FIXTURE, minimalState()]) {
    for (const script of [generateRScript(state), generatePyGMT(state)]) {
      assert.ok(!script.includes('WIDTH'), 'no WIDTH token');
      assert.ok(!script.includes('undefined'), 'no leaked undefined');
      assert.ok(!script.includes('NaN'), 'no leaked NaN');
      assert.ok(!script.includes('${'), 'no unexpanded template literal');
      assert.ok(!script.includes('[object Object]'), 'no stringified object');
    }
  }
});

test('R: emitted scripts parse as real R syntax when Rscript is available', (t) => {
  const probe = spawnSync('Rscript', ['--version'], { encoding: 'utf8' });
  if (probe.error || probe.status !== 0) {
    t.skip('Rscript not available on PATH');
    return;
  }
  const dir = fs.mkdtempSync(path.join(process.env.TMPDIR ?? '/tmp', 'mmt-scripts-r-'));
  try {
    for (const [label, state] of [
      ['full', FIXTURE],
      ['minimal', minimalState()],
    ]) {
      const file = path.join(dir, `figure-${label}.R`);
      fs.writeFileSync(file, generateRScript(state), 'utf8');
      const run = spawnSync('Rscript', ['-e', `invisible(parse("${file}"))`], {
        encoding: 'utf8',
      });
      assert.equal(run.status, 0, `R parse failed for ${label} state:\n${run.stderr}`);
    }
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

/* ------------------------------------------------------------- shared ---- */

test('both generators are deterministic (byte-identical on repeat calls)', () => {
  assert.equal(generatePyGMT(FIXTURE), generatePyGMT(FIXTURE));
  assert.equal(generateRScript(FIXTURE), generateRScript(FIXTURE));
});

test('both generators reject malformed states', () => {
  for (const gen of [generatePyGMT, generateRScript]) {
    assert.throws(() => gen(null), TypeError);
    assert.throws(() => gen({}), TypeError);

    const noWidth = structuredClone(FIXTURE);
    noWidth.projection.gmt = '-JM16c'; // already substituted — not a template
    assert.throws(() => gen(noWidth), TypeError, 'missing WIDTH token');

    const badRegion = structuredClone(FIXTURE);
    badRegion.region.north = Number.NaN;
    assert.throws(() => gen(badRegion), TypeError);

    const inverted = structuredClone(FIXTURE);
    inverted.region.south = 50; // south >= north
    assert.throws(() => gen(inverted), RangeError);
  }
});

test('committed sample scripts in /scripts are in sync with the generators', () => {
  const scriptsDir = path.resolve(import.meta.dirname, '..', '..', 'scripts');
  const pyPath = path.join(scriptsDir, 'example-figure.py');
  const rPath = path.join(scriptsDir, 'example-figure.R');
  assert.ok(fs.existsSync(pyPath), `${pyPath} missing — regenerate per scripts/README.md`);
  assert.ok(fs.existsSync(rPath), `${rPath} missing — regenerate per scripts/README.md`);
  assert.equal(
    fs.readFileSync(pyPath, 'utf8'),
    generatePyGMT(FIXTURE),
    'example-figure.py is stale — regenerate it from the fixture (see scripts/README.md)',
  );
  assert.equal(
    fs.readFileSync(rPath, 'utf8'),
    generateRScript(FIXTURE),
    'example-figure.R is stale — regenerate it from the fixture (see scripts/README.md)',
  );
});
