#!/usr/bin/env Rscript
# ============================================================================
# Reproducible marine map figure — generated by Marine Map Tool
#
# Journal target : Deep-Sea Research Part I
#   width 168 mm | 600 dpi | PDF
# Suggested projection : Lambert conformal conic
#   Conformal conic projection; scale is true along the two standard parallels
#   (32.7° and 43.3°), ideal for east–west elongated mid-latitude regions.
#
# NOTE: coord_sf() below draws in plate carrée (unprojected WGS84 lon/lat).
#       To render the figure in the suggested projection above, use the
#       companion PyGMT script exported alongside this one.
#
# Cite the data and colormaps used in this figure:
#   GEBCO Compilation Group (2024). The GEBCO_2024 Grid. NERC EDS British
#   Oceanographic Data Centre NOC.
#   doi:10.5285/1c44ce99-0a0d-5f4f-e063-7086abc0ea0f
#   Thyng, K. M., Greene, C. A., Hetland, R. D., Zimmerle, H. M., & DiMarco,
#   S. F. (2016). True colors of oceanography: Guidelines for effective and
#   accurate colormap selection. Oceanography, 29(3), 9-13.
#   doi:10.5670/oceanog.2016.66
#   NOAA National Centers for Environmental Information (2022). ETOPO 2022 15
#   Arc-Second Global Relief Model. doi:10.25921/fd45-gt74
# Data accessed  : 2026-07-05
#
# install.packages(c("terra", "sf", "ggplot2", "cmocean",
#                    "rnaturalearth", "rnaturalearthdata", "ggspatial"))
# ============================================================================

library(terra)
library(sf)
library(ggplot2)
library(ggspatial)

# --- Bathymetry: ETOPO 2022 (15 arc-second) subset from NOAA ERDDAP ---------
# griddap slice order is z[(south):stride:(north)][(west):stride:(east)].
# stride 5 keeps the grid ≈2016 columns wide (raise for more detail).
bathy_url <- paste0(
  "https://coastwatch.pfeg.noaa.gov/erddap/griddap/ETOPO_2022_v1_15s.nc",
  "?z%5B(30):5:(46)%5D%5B(-6):5:(36)%5D"
)
download.file(bathy_url, destfile = "bathy.nc", mode = "wb")

bathy <- terra::rast("bathy.nc")
bathy_df <- as.data.frame(bathy, xy = TRUE)
names(bathy_df) <- c("lon", "lat", "z")

# Land polygons (Natural Earth, medium scale) drawn over the raster so land
# masks the offshore relief.
land <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")

# Stations (2).
stations <- data.frame(
  lon = c(21.13, 21.38),
  lat = c(36.57, 35.3),
  name = c("Calypso Deep", "L'Atalante Basin"),
  value = c(-5267, -3600)
)

p <- ggplot() +
  geom_raster(data = bathy_df, aes(x = lon, y = lat, fill = z)) +
  # cmocean "deep" — the same perceptually uniform colormap as
  # the on-screen preview. The fill axis is elevation (deep = minimum), so the
  # direction is inverted relative to the on-screen "reverse" toggle.
  scale_fill_gradientn(
    colours = cmocean::cmocean("deep", direction = -1)(256),
    limits = c(-6000, 0),
    oob = scales::squish,
    name = "Elevation (m)"
  ) +
  geom_contour(
    data = bathy_df,
    aes(x = lon, y = lat, z = z),
    breaks = seq(-6000, 0, by = 500),
    colour = "gray40",
    linewidth = 0.2
  ) +
  geom_sf(data = land, fill = "#e8e5e0", colour = "gray30", linewidth = 0.2) +
  geom_point(
    data = stations,
    aes(x = lon, y = lat),
    shape = 21,
    size = 2.5,  # symbol diameter in mm
    fill = "#e4572e",
    colour = "black",
    stroke = 0.4
  ) +
  geom_text(
    data = stations,
    aes(x = lon, y = lat, label = name),
    hjust = -0.3,
    size = 7 / .pt,  # 7 pt labels
    family = "Helvetica"
  ) +
  # 5° graticule.
  scale_x_continuous(breaks = seq(-5, 35, by = 5)) +
  scale_y_continuous(breaks = seq(30, 45, by = 5)) +
  annotation_scale(location = "bl") +
  annotation_north_arrow(
    location = "tr",
    height = unit(0.9, "cm"),
    width = unit(0.9, "cm")
  ) +
  # Plate carrée frame; see the header for the suggested projection.
  coord_sf(
    xlim = c(-6, 36),
    ylim = c(30, 46),
    expand = FALSE,
    crs = sf::st_crs(4326)
  ) +
  labs(title = "Mediterranean Sea — Bathymetry and Stations") +
  theme_minimal(base_size = 8, base_family = "Helvetica")

# Final physical width: 168 mm at 600 dpi.
ggsave("marine_map.pdf", plot = p, width = 168, units = "mm", dpi = 600)
