#!/usr/bin/env python3
# ============================================================================
# Reproducible marine map figure — generated by Marine Map Tool
#
# Journal target : Deep-Sea Research Part I
#   width 168 mm | 600 dpi | PDF
# Projection     : Lambert conformal conic
#   Conformal conic projection; scale is true along the two standard parallels
#   (32.7° and 43.3°), ideal for east–west elongated mid-latitude regions.
#
# Cite the data and colormaps used in this figure:
#   GEBCO Compilation Group (2024). The GEBCO_2024 Grid. NERC EDS British
#   Oceanographic Data Centre NOC.
#   doi:10.5285/1c44ce99-0a0d-5f4f-e063-7086abc0ea0f
#   Thyng, K. M., Greene, C. A., Hetland, R. D., Zimmerle, H. M., & DiMarco,
#   S. F. (2016). True colors of oceanography: Guidelines for effective and
#   accurate colormap selection. Oceanography, 29(3), 9-13.
#   doi:10.5670/oceanog.2016.66
#   NOAA National Centers for Environmental Information (2022). ETOPO 2022 15
#   Arc-Second Global Relief Model. doi:10.25921/fd45-gt74
# Data accessed  : 2026-07-05
#
# pip install pygmt  (or conda install -c conda-forge pygmt)
# ============================================================================

import pygmt

# Region of interest (degrees, WGS84) in GMT order: [west, east, south, north].
region = [-6, 36, 30, 46]

# Physical width from the journal target: 168 mm = 16.8 cm.
# GMT -J projection value (PyGMT takes it without the "-J" prefix).
projection = "L15/38/32.7/43.3/16.8c"

# Earth relief resolution chosen from the 42° longitude span.
grid = pygmt.datasets.load_earth_relief(resolution="02m", region=region)

fig = pygmt.Figure()

# GMT >= 6 ships the cmocean colormaps natively, so the name resolves directly.
# The on-screen tool maps colormap position 0 to the SHALLOW end, but the CPT
# series here runs over elevation (deep = minimum), so the direction flag is
# inverted relative to the on-screen "reverse" toggle.
pygmt.makecpt(cmap="deep", series=[-6000, 0], reverse=True)

fig.grdimage(
    grid=grid,
    cmap=True,
    region=region,
    projection=projection,
    shading="+a315+nt0.6",
)

# Coastlines and land fill AFTER grdimage so land masks the offshore relief.
fig.coast(shorelines="1/0.25p,gray30", land="#e8e5e0")

# Depth contours every 500 m, annotated every 1000 m (seafloor only).
fig.grdcontour(
    grid=grid,
    levels=500,
    annotation=1000,
    limit=[-6000, 0],
    pen="0.25p,gray40",
)

# Stations (2); symbol diameter 2.5 mm.
station_lons = [21.13, 21.38]
station_lats = [36.57, 35.3]
station_names = ["Calypso Deep", "L'Atalante Basin"]
fig.plot(
    x=station_lons,
    y=station_lats,
    style="c0.25c",
    fill="#e4572e",
    pen="0.5p,black",
)
for lon, lat, name in zip(station_lons, station_lats, station_names):
    fig.text(x=lon, y=lat, text=name, justify="LM", offset="0.25c/0c", font="7p,Helvetica,black")

# Frame with 5° graticule annotations.
fig.basemap(frame=["xa5f", "ya5f", "WSen+t\"Mediterranean Sea — Bathymetry and Stations\""])

# Scale bar: ~1/4 of the region width at the centre latitude, rounded to 1000 km.
fig.basemap(map_scale="jBL+w1000k+o0.4c/0.4c+f+lkm")

# North arrow.
fig.basemap(rose="jTR+w1.1c+o0.3c")

fig.colorbar(frame="xaf+l\"Elevation (m)\"")

# Global-overview inset with the mapped region outlined in red.
with fig.inset(position="jTL+w3.2c+o0.25c", box="+gwhite+p0.5p"):
    fig.coast(region="g", projection="G15/38/3.2c", land="gray80", water="white")
    fig.plot(
        data=[
            [-6, 30],
            [36, 30],
            [36, 46],
            [-6, 46],
            [-6, 30],
        ],
        pen="1p,red",
    )

# Final physical width: 168 mm (16.8 cm) at 600 dpi.
fig.savefig("marine_map.pdf", dpi=600)
